// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vn1-0KJ9W7ItlQVpnQWpEf9ZhtUdQvw',
    appId: '1:978534933529:web:b2b2ec1d211256314d7688',
    messagingSenderId: '978534933529',
    projectId: 'check-6c651',
    authDomain: 'check-6c651.firebaseapp.com',
    storageBucket: 'check-6c651.firebasestorage.app',
    measurementId: 'G-1W12QY14Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhu00dHXNd7KvE-eMGGnwzGiAPVbF0jcU',
    appId: '1:978534933529:android:33d67a12331f7aa24d7688',
    messagingSenderId: '978534933529',
    projectId: 'check-6c651',
    storageBucket: 'check-6c651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARgMuOinw1nFswpqBQzia2W_XNt_39MPA',
    appId: '1:978534933529:ios:cb3219718150b7bd4d7688',
    messagingSenderId: '978534933529',
    projectId: 'check-6c651',
    storageBucket: 'check-6c651.firebasestorage.app',
    androidClientId: '978534933529-52mtpinevac68kgslp3gtdfb0gr1o4aa.apps.googleusercontent.com',
    iosClientId: '978534933529-1nf810d1a1behg9sro1ndn0mjmqkim3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseGoogleSignin',
  );

}